const students = [
  "Abdullah Almalki",
  "Abdullah Alnuwaysir",
  "Ahad ALShammari",
  "Almaha Alsaif",
  "Amjad Alharkan",
  "Amerah Aljaidi",
  "Azzah Mukhtar",
  "Bashayer Ali Bin Muattish",
  "Duha Alkhabbaz",
  "Ghadah Alotaibi",
  "Hind Alayed",
  "Haya Alanzi",
  "Hawraa Almodhhi",
  "Hessa Alshalani",
  "Khulood Fahad",
  "Lama Alosaimi",
  "Manal Alsaqer",
  "Manar Al Sannaa",
  "Maytha Alamri",
  "Meead Alotaibi",
  "Muhannad Alwagdani",
  "Muna Alrajhi",
  "Nimah Bishr",
  "Norah Sumayli",
  "Nouf Alshehri",
  "Noura Aljaloud",
  "Nuha alrabiah",
  "Osama Fatani",
  "Raniah Almetani",
  "Refah Aldossary",
  "Salwa Alahmadi",
  "Sara Alalshaikh",
  "Sarah Alshaikhmubarak",
  "Sarah Fatani",
  "Tahani Alqahtani",
  "shaikah Bin Moqbel",
  "Wejdan Alshareef"
]

export default students
